export const actions = {
  ADD_TODO_ITEM: "ADD_TODO_ITEM",
  REMOVE_TODO_ITEM: "REMOVE_TODO_ITEM",
  TOGGLE_COMPLETED: "TOGGLE_COMPLETED",
  ADD_NEW_CITY_WEATHER: "ADD_NEW_CITY_WEATHER",
  CLEAR_CITY_WEATHER: "CLEAR_CITY_WEATHER",
};
